<a href="https://colab.research.google.com/github/MangeshGawas/All_About_Python_AI_ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem statement 1

Given a list lst perform elementwise addition with 5.


In [12]:
lst = [5, 10, 0, 200]

import numpy as np
arr = np.array(lst)
print(arr+5)


[ 10  15   5 205]


In [17]:
import numpy as np

lst = [1, 2, 3, "text", True, 3+2j]
arr = np.array(lst)

for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Problem statement 3

Given a list lst find its complete size in bytes. Hint: use sys.getsizeof(lst)

In [18]:
lst = [56,45,12,6]
import numpy as np
arr=np.array(lst)
print(arr.nbytes)

32


**NumPy object creation**

In [19]:
arr = np.array([2,6,7,4],dtype=int)
print(arr)

print(type(arr))

print(np.result_type(arr))

[2 6 7 4]
<class 'numpy.ndarray'>
int64


In [23]:
''' Creation of an array with step size 1.33 between 0 - 10 '''
print(np.arange(0, 10, 1.33, dtype = np.float64))

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]


In [24]:

''' Creation of an array with total 5 values between 0 - 160 '''
print(np.linspace(0,160,5,dtype=np.float64))

[  0.  40.  80. 120. 160.]


**Matrix Creation**


In [33]:
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(2,3))

''' Method II: Using matrix function '''
print(np.matrix([[1,2,3],[12,13,14]]))

''' Method III: Using misc. functions '''
print(np.eye(3))

print(np.zeros((4,3)))

print(np.ones((3,3),dtype = np.float64))


[[ 5  6  8]
 [45 12 52]]
[[ 1  2  3]
 [12 13 14]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Given two NumPy arrays arr1 = [25, 56, 12, 85, 34, 75] and arr2 = [42, 3, 86, 32, 856, 46], solve the following:

Create a new NumPy array Narr with the shape equal to arr1 filled with random values.

Permanently change the dtype of arr1 to complex.

Transform arrays arr1 and arr2 into two matrices (arr1_mat and arr2_mat) of shape (2,3) and arrive at the solution of the following equation:

In [40]:
import numpy as np
arr1 = np.array([25, 56, 12, 85, 34, 75])
arr2 = np.array([42, 3, 86, 32, 856, 46])

#solution 1
Narr = np.random.rand(*arr1.shape)
print(Narr)

#solution 2
arr1 = arr1.astype(complex)
print(arr1)

#solution
arr1_mat = arr1.reshape(2, 3)
arr2_mat = arr2.reshape(2, 3)
result = np.matmul(arr1_mat, arr2_mat.T) #cross multiplication
print(result)


[0.67677535 0.88994219 0.17487111 0.54826396 0.38102523 0.82715026]
[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]
[[ 2250.+0.j 49288.+0.j]
 [10122.+0.j 35274.+0.j]]


In [41]:
import numpy as np
arr = np.arange(4)
arr.reshape(2,2)
print(arr.shape)


(4,)


In [43]:
import numpy as np
arr = np.arange(4).reshape(4,-1)
print(arr.shape)

(4, 1)


In [44]:
import numpy as np

arr1 = np.ones(10)
arr2 = np.arange(10, dtype = np.float64)
arr3 = arr1 + arr2
print(np.result_type(arr1))
print(np.result_type(arr3))

float64
float64


# Vectorized operations

In [50]:

S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)

#Difference of each vector
print(S_Y - S_X)

#Less than 2
print(S_X < 2)

''' Method 2 '''
#comparing matrix
twos_mat = np.ones((2, 4)) * 2
print(twos_mat)
print(np.less(S_Y, twos_mat))




[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]
[[ 4  2 -1  4]
 [ 3 -3  0 -1]]
[[False False False False]
 [False False False False]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[False False False False]
 [False False False False]]


Solve the following:

Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.

Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10.

Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.


In [54]:
#solution 1
matrix = np.zeros((4,4),dtype=int)
matrix[0, 0] = 4
matrix[1, 1] = 5
matrix[2, 2] = 6
print(matrix)


[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 0]]


Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.

In [56]:

import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl'])

for i in range(len(arr)):
    if mat[i, 0] == arr[i]:
        print(mat[i, 1])


A
C


In [60]:
#4. Given a matrix mat, sort it by the second column.
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
sorted_mat = mat[mat[:, 1].argsort()]
print("Original matrix:")
print(mat)
print("\nSorted matrix by the second column:")
print(sorted_mat)

Original matrix:
[[ 1  4  3]
 [ 5 12  2]
 [56 21  4]]

Sorted matrix by the second column:
[[[ 1  4  3]
  [ 5 12  2]
  [56 21  4]]]


In [62]:
#Given an array arr, find the top 4 maximum values.
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
indices = np.argpartition(arr, -4)[-4:]

top_four = arr[indices]
print(top_four)


[ 45  50 590  90]


In [65]:
#6. Find the nearest number from the given number in an array.
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50
abs_diff = np.abs(arr - nearest_to)
nearest_index = abs_diff.argmin()
nearest_number = arr[nearest_index]

nearest_number = arr[nearest_index]

print("Array:", arr)
print("Nearest number to", nearest_to, "is:", nearest_number)


Array: [10 55 22  3  6 44  9 54]
Nearest number to 50 is: 54
