<a href="https://colab.research.google.com/github/MangeshGawas/All_About_Python_AI_ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem statement 1

Given a list lst perform elementwise addition with 5.


In [12]:
lst = [5, 10, 0, 200]

import numpy as np
arr = np.array(lst)
print(arr+5)


[ 10  15   5 205]


In [17]:
import numpy as np

lst = [1, 2, 3, "text", True, 3+2j]
arr = np.array(lst)

for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Problem statement 3

Given a list lst find its complete size in bytes. Hint: use sys.getsizeof(lst)

In [18]:
lst = [56,45,12,6]
import numpy as np
arr=np.array(lst)
print(arr.nbytes)

32


**NumPy object creation**

In [19]:
arr = np.array([2,6,7,4],dtype=int)
print(arr)

print(type(arr))

print(np.result_type(arr))

[2 6 7 4]
<class 'numpy.ndarray'>
int64


In [23]:
''' Creation of an array with step size 1.33 between 0 - 10 '''
print(np.arange(0, 10, 1.33, dtype = np.float64))

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]


In [24]:

''' Creation of an array with total 5 values between 0 - 160 '''
print(np.linspace(0,160,5,dtype=np.float64))

[  0.  40.  80. 120. 160.]


**Matrix Creation**


In [33]:
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(2,3))

''' Method II: Using matrix function '''
print(np.matrix([[1,2,3],[12,13,14]]))

''' Method III: Using misc. functions '''
print(np.eye(3))

print(np.zeros((4,3)))

print(np.ones((3,3),dtype = np.float64))


[[ 5  6  8]
 [45 12 52]]
[[ 1  2  3]
 [12 13 14]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
